services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: tasktracker-rabbit
    ports:
      - "5672:5672"       # AMQP
      - "15672:15672"     # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin